### ISSUE TITLE
Regression: Remember me stopped working in 0.6.5

### ISSUE THREAD

**Issue by jochenberger** [tynamo/tapestry-security#30]
If I check "remember me", upon login I get
```
org.apache.shiro.crypto.CryptoException: Unable to init cipher instance.
	at org.apache.shiro.crypto.JcaCipherService.init(JcaCipherService.java:495)
	at org.apache.shiro.crypto.JcaCipherService.initNewCipher(JcaCipherService.java:598)
	at org.apache.shiro.crypto.JcaCipherService.crypt(JcaCipherService.java:444)
	at org.apache.shiro.crypto.JcaCipherService.encrypt(JcaCipherService.java:324)
	at org.apache.shiro.crypto.JcaCipherService.encrypt(JcaCipherService.java:313)
	at org.apache.shiro.mgt.AbstractRememberMeManager.encrypt(AbstractRememberMeManager.java:463)
	at org.apache.shiro.mgt.AbstractRememberMeManager.convertPrincipalsToBytes(AbstractRememberMeManager.java:352)
	at org.apache.shiro.mgt.AbstractRememberMeManager.rememberIdentity(AbstractRememberMeManager.java:336)
	at org.apache.shiro.mgt.AbstractRememberMeManager.rememberIdentity(AbstractRememberMeManager.java:311)
	at org.apache.shiro.mgt.AbstractRememberMeManager.onSuccessfulLogin(AbstractRememberMeManager.java:287)
	at $RememberMeManager_b697f32e0c8.onSuccessfulLogin(Unknown Source)
	at org.apache.shiro.mgt.DefaultSecurityManager.rememberMeSuccessfulLogin(DefaultSecurityManager.java:206)
	at org.apache.shiro.mgt.DefaultSecurityManager.onSuccessfulLogin(DefaultSecurityManager.java:291)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:285)
	at $WebSecurityManager_b697f32e0bb.login(Unknown Source)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
	at org.tynamo.security.components.LoginForm.attemptToLogin(LoginForm.java:122)
[snip]
Caused by: java.security.InvalidKeyException: Invalid AES key length: 93 bytes
	at com.sun.crypto.provider.AESCrypt.init(AESCrypt.java:87)
	at com.sun.crypto.provider.CipherBlockChaining.init(CipherBlockChaining.java:91)
	at com.sun.crypto.provider.CipherCore.init(CipherCore.java:582)
	at com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:339)
	at javax.crypto.Cipher.implInit(Cipher.java:806)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.apache.shiro.crypto.JcaCipherService.init(JcaCipherService.java:488)
	... 135 common frames omitted
```
The remember me functionality does not work, I'm logged out when my session expires.

**Comment by jochenberger** [comment]
probably related to #29, I have a HMAC passphrase configured.

**Comment by jochenberger** [comment]
It's probably not a good idea to try to use the HMAC passphrase as a fallback because its key length is too variable.

**Comment by kaosko** [comment]
Yes, I noticed. Thought I had a test for covering the case so went ahead with the release too quickly. I still think there's value in getting this done with zero additional configuration, I see if it's reasonable to add sufficient padding.

**Comment by kaosko** [comment]
Whether hmac is a good key or not is almost irrelevant, because only known types can serialized. I claim this implementation is far superior to what Shiro current provides by default.
